---
driver:
  name: ec2
  aws_ssh_key_id: chef_demo_2x
  region: us-west-2
  security_group_ids: sg-2560a741
  associate_public_ip: true
  instance_type: m3.large
  tags:
    Name: "FourthCoffee Test Kitchen Instance"
    created-by: "test-kitchen"
    user: Administrator

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 1

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows-2012r2
    driver_config:
      retryable_tries: 80
    transport:
      ssh_key: C:\Users\chef\.ssh\id_rsa

suites:
  - name: default
    run_list:
      - recipe[myiis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      #sql_server:
        #server_sa_password: SQL_sa_pa$$w0rd

